name: Snapthat Portrait Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6976480702869594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f8fdfe'
    - '#788a00'
    - '#008598'
    - '#d7a8a0'
  brandStrength: 0.7388328544329852
  lightness: 0.30704449652694166
  saturation: 0.08674888825044036
  rhythmicContrast: 0.11874433606863022
purpose: []
